package com.calculadora.util.enums;

public enum TipoMoedas {
	REAL("Real (Brasil)", "BRL", "R$"),
	DOLAR("Dólar (US)", "USD", "$"),
	EURO("Euro", "EUR", "€"),
	EMIRADO_ARABES("Emirados Arabes Unidos", "AED", "د.إ"),
	AFEGANE("Afegane (Afeganistão)", "AFN", "؋"),
	LEK("Lek (Albânia)", "ALL", "L"),
	DRAM("Dram (Armênia)", "AMD", "֏"),
	FLORIM("Florim antilhano (Curaçau)", "ANG", "ƒ"),
	KWANZA("Kwanza Angolano ", "AOA", "Kz"),
	PESO("Peso Argentino", "ARS", "$"),
	DOLAR_AUSTR("Dólar Australiano", "AUD", "$"),
	ARUBA("Florim Arubano", "AWG", "ƒ"),
	MANAT_AZERB("Manat Azerbaijano", "AZN", "m"),
	MARCO("Marco convertível da Bósnia e Herzegovina", "BAM", "KM "),
	DOLAR_BARB("Dólar dos Barbados", "BBD", "$"),
	TAKA("Taka Bangladexense", "BDT", "৳"),
	LEV("Lev Búlgaro", "BGN", "лв"),
	DINAR_BARENITA("Dinar Barenita", "BHD", ".د.ب"),
	FRANCO("Franco Burundiano", "BIF", "Fr"),
	DOLAR_BERMU("Dólar bermudense", "BMD", "$"),
	DOLAR_BRUNEI("Dólar do Brunei", "BND", "$"),
	BOLIVIANO("Boliviano", "BOB", "Bs."),
	DOLAR_BAAMEN("Dólar baamense", "BSD", "$"),
	BITCOIN("Bitcoin", "BTC", "Ƀ"),
	NGULTRUM("Ngultrum Butanês", "BTN", "Nu."),
	PULA("Pula do Botsuana (Zimbábue)", "BWP", "P"),
	RUBLO_BIEL("Rublo Bielorrusso", "BYR", "Br"),
	DOLAR_BELIZE("Dólar do Belize", "BZD", "$"),
	DOLAR_CANADA("Dólar canadiano (Canadá)", "CAD", "$"),
	FRANCO_CONGOLES("Franco congolês", "CDF", "Fr"),
	FRANCO_SUICO("Franco suíço", "CHF", "Fr"),
	UNIDAD_FOMENTO("Unidad de Fomento chilena ", "CLF", "UF"),
	PESO_CHIL("Peso chileno", "CLP", "$"),
	OFFSHORE_YUAN("Offshore Yuan chinês", "CNH", "¥"),
	IUANE("Iuane chinês", "CNY", "¥"),
	PESO_COLOM("Peso colombiano", "COP", "$"),
	COLON("Colón costarriquenho", "CRC", "₡"),
	PESO_CUBA("Peso cubano", "CUP", "$"),
	ESCUDO_CAB_V("Escudo cabo-verdiano", "CVE", "$"),
	COROA_CHECA("Coroa checa", "CZK", "Kč"),
	MARK("Marco Alemão (Mark)", "DEM", "DM"),
	FRANCO_JIBUT("Franco jibutiano", "DJF", "Fr"),
	COROA_DINARMAQUESA("Coroa dinamarquesa", "DKK", "kr"),
	PESO_DOMINIC("Peso dominicano", "DOP", "$"),
	DINAR_ARGEL("Dinar argelino", "DZD", "د.ج"),
	LIBRA_EGIPCIA("Libra egípcia", "EGP", "£"),
	NAKFA_ERITREIA("Nakfa eritreia", "ERN", "Nfk"),
	BIRR_ETIOPE("Birr etíope", "ETB", "Br"),
	MARKKA("Markka finlandesa", "FIM", "mk"),
	DOLAR_FIJIANO("Dólar fijiano", "FJD", "$"),
	LIBRA_ILHAS_MALV("Libra das Ilhas Malvinas", "FKP", "£"),
	FRANCO_FRANCES("Franco francês", "FRF", "Fr"),
	LIBRA_ESTERLINA("Libra esterlina", "GBP", "£"),
	LARI_GEORGIANO("Lari georgiano", "GEL", "د.ج"),
	CEDI_GANA("Cedi do Gana", "GHS", "₵"),
	LIBRA_GIBRALTAR("Libra de Gibraltar", "GIP", "£"),
	DALASI_GAMBIANO("Dalasi gambiano", "GMD", "D"),
	FRANCO_GUINEENSE("Franco guineense", "GNF", "Fr"),
	QUETZAL("Quetzal guatemalteco", "GTQ", "Q"),
	DOLAR_GUIANENSE("Dólar guianense", "GYD", "$"),
	DOLAR_HONGUECONGUE("Dólar de Honguecongue", "HKD", "$"),
	LEMPIRA_HONDURENHA("Lempira hondurenha", "HNL", "L"),
	KUNA_CROATA("Kuna croata", "HRK", "kn"),
	GURDE_HAITIANO("Gurde haitiano", "HTG", "G"),
	FLORIM_HUNGARO("Florim húngaro", "HUF", "Ft"),
	RUPIA_INDONESIA("Rupia indonésia", "IDR", "Rp"),
	LIBRA_IRLANDESA("Libra irlandesa", "IEP", "£"),
	NOVO_SICLO_ISRAE("Novo siclo israelita", "ILS", "﷼"),
	RUPIA("Rupia indiana", "INR", "₹"),
	DINAR_IRAQUE("Dinar iraquiano", "IQD", "ع.د"),
	RIAL_IRA("Rial iraniano", "IRR", "﷼"),
	COROA_ISLANDESA("Coroa islandesa", "ISK", "kr"),
	LIRA_ITALIANA("Lira italiana", "ITL", "₤"),
	DOLAR_JAMAICO("Dólar jamaicano", "JMD", "$"),
	DINAR_JORDNO("Dinar jordano", "JOD", "د.ا"),
	IENE_JAPAO("Iene japonês", "JPY", "¥"),
	XELIM_QUENIANO("Xelim queniano", "KES", "Sh"),
	SOM_QUIRGUIZ("Som quirguiz", "KGS", "лв"),
	RIEL_CAMBOJANO("Riel cambojano", "KHR", "៛"),
	FRANCO_COMORENSE("Franco comorense", "KMF", "Fr"),
	WON_COREIA_NORTE("Won norte-coreano", "KPW", "₩"),
	WON_COREIA_SUL("Won sul-coreano", "KRW", "₩"),
	DINAR_CUAITIANO("Dinar cuaitiano", "KWD", "د.ك"),
	DOLAR_ILHAS_CAIMAO("Dólar das Ilhas Caimão", "KYD", "$"),
	TENGUE("Tengue cazaque", "KZT", "₸"),
	KIPE("Kipe lau", "LAK", "₭"),
	LIBRA_LIBANESA("Libra libanesa", "LBP", "ل.ل"),
	RUPIA_CINGALESA("Rupia cingalesa", "LKR", "රු"),
	DOLAR_LIBERIANO("Dólar liberiano", "LRD", "$"),
	LOTI("Loti do Lesoto", "LSL", "L"),
	LITA("Lita Lituanesa", "LTL", "Lt "),
	LATS("Lats letão", "LVL", "Ls"),
	DINAR_LIBIO("Dinar líbio", "LYD", "ل.د"),
	DIRAME("Dirame marroquino", "MAD", "د.م."),
	LEU("Leu moldávio", "MDL", "L"),
	ARIARI("Ariari malgaxe", "MGA", "Ar"),
	DINAR_MACEDONIO("Dinar macedónio", "MKD", "ден"),
	KYAT("Kyat de Mianmar", "MMK", "Ks"),
	TUGRIK("Tugrik mongol", "MNT", "₮"),
	PATACA("Pataca macaense", "MOP", "P"),
	UGUIA("Uguia mauritana", "MRO", "UM"),
	RUPIA_MAURICIA("Rupia maurícia", "MUR", "₨"),
	RUPIA_MALDIVA("Rupia maldiva", "MVR", ".ރ"),
	KWACHA_MALAUIANO("Kwacha malauiano", "MWK", "MK"),
	PESO_MEXICANO("Peso mexicano", "MXN", "$"),
	RINGUITE_MALAIO("Ringuite malaio", "MYR", "RM"),
	METICAL_MOCAMBI("Metical moçambicano", "MZN", "MT"),
	DOLAR_NAMIBIANO("Dólar namibiano", "NAD", "$"),
	NAIRA_NIGERIANO("Naira nigeriano", "NGN", "₦"),
	CORDOBA("Córdoba nicaraguano", "NIO", "C$"),
	COROA_NORUEGUA("Coroa norueguesa", "NOK", "kr"),
	RUPIA_NEPALESA("Rupia nepalesa", "NPR", "₨"),
	DOLAR_NOVA_ZELANDIA("Dólar da Nova Zelândia", "NZD", "$"),
	RIAL_OMANENSE("Rial omanense", "OMR", "ر.ع."),
	BALBOA("Balboa panamense", "PAB", "B/."),
	NOVO_SOL("Novo sol peruano", "PEN", "S/."),
	KIBA("Kina papuásia", "PGK", "K"),
	PESO_FILIPINO("Peso filipino", "PHP", "₱"),
	KINA_PAPUA("Kina de Papua Nova Guiné", "PKG", "K"),
	RUPIA_PAQUISTANESA("Rupia paquistanesa", "PKR", "₨"),
	ZLOTI("Zlóti polaco", "PLN", "zł"),
	GUARANI("Guarani paraguaio", "PYG", "₲"),
	RIAL("Rial catarense", "QAR", "ر.ق"),
	DOLAR_MICRON("Dólar micronésio[", "RON", "lei"),
	DINAR_SERVIO("Dinar sérvio", "RSD", "дин."),
	RUBO_RUSSO("Rublo Russo", "RUB", "р."),
	FRANCO_RUANDES("Franco ruandês", "RWF", "Fr"),
	RIAL_SAUDITA("Rial saudita", "SAR", "ر.س"),
	DOLAR_ILHAS_SALOMAO("Dólar das Ilhas Salomão", "SBD", "$"),
	RUPIA_SEICHELENSE("Rupia seichelense", "SCR", "₨"),
	LIBRA_SUDANESA("Libra sudanesa", "SDG", "£"),
	LIBRA_SANTA_HELENA("Libra de Santa Helena", "SHP", "£"),
	COROA_CHEC("Coroa Checa", "SKK", "Sk"),
	LEONE_SERRA_LEONINO("Leone serra-leonino", "SLL", "Le"),
	XELIM_SOMALIANO("Xelim somaliano", "SOS", "Sh"),
	DOLAR_SURINAMES("Dólar surinamês", "SRD", "$"),
	DOBRA_SAO_TOME("Dobra de São Tomé e Príncipe", "STD", "Db"),
	COLEN_EL_SALVADOR("Cólon El Salvador", "SVC", "₡"),
	LIBRA_SIRIA("Libra síria", "SYP", "£"),
	LILANGENI("Lilangeni suazilandês", "SZL", "L"),
	BAHT("Baht tailandês", "THB", "฿"),
	SOMONI("Somoni tajique", "TJS", "ЅМ"),
	MANAT("Manat turcomeno", "TMT", "m"),
	DINAR("Dinar tunisino", "TND", "د.ت"),
	PA_ANGA("Pa'anga tonganesa", "TOP", "T$"),
	LIRA_TURCA("Lira turca", "TRY", "₺"),
	DOLAR_TRINDADE("Dólar de Trindade e Tobago", "TTD", "$"),
	NOVO_DOLAR_TAIUA("Novo dólar de Taiuã", "TWD", "$"),
	XELIM_TANZ("Xelim tanzaniano", "TZS", "Sh"),
	GRIVNIA_UCRANIANA("Grívnia ucraniana", "UAH", "₴"),
	XELIM("Xelim ugandês", "UGX", "Sh"),
	PESO_URUGUAIO("Peso uruguaio", "UYU", "$"),
	SOM_USABEQUE("Som usbeque", "UZS", "лв"),
	BOLIVIAR_VENEZ("Bólivar venezuelano", "VEF", "BsF"),
	DONGUE("Dongue vietnamita", "VND", "₫"),
	VATU("Vatu do Vanuatu", "VUV", "Vt"),
	TALA("Tala samoana", "WST", "T"),
	FRANCO_cfa("Franco CFA BEAC", "XAF", "Fr"),
	DOLAR_CARAIBAS("Dólar das Caraíbas Orientais", "XCD", "$"),
	DIREITOS_ESP_FMI("Direitos Especiais de Saque do FMI", "XDR", "XDR"),
	FRANCO_CFA("Franco CFA BCEAO", "XOF", "Fr"),
	FRANCO_CPF("Franco CFP (Nova Caledónia)", "XPF", "Fr"),
	RIAL_IEMITA("Rial iemenita", "YER", "﷼"),
	RAND_SUL_AFRICANO("Rand sul-africano", "ZAR", "R"),
	KWACHA_ZAMBIANO_68("Kwacha zambiano (1968–2012)", "ZMK", "ZK"),
	KWACHA("Kwacha zambiano", "ZMW", "ZMW"),
	DOLAR_ZAMBIANO_2009("Dolar zambiano (2009)", "ZWL", "ZWL");
	
	private String nomeMoeda;
	private String codigoISO;
	private String simbolo;
	
	private TipoMoedas(String nomeMoeda, String codigoISO, String simbolo) {
		this.nomeMoeda = nomeMoeda;
		this.codigoISO = codigoISO;
		this.simbolo = simbolo;
	}
	
	public String getCodigoISO() {
		return codigoISO;
	}
	
	public String getNomeMoeda() {
		return nomeMoeda;
	}
	
	public String getSimbolo() {
		return simbolo;
	}
	
	@Override
	public String toString() {
		return "[" + codigoISO + "] " + nomeMoeda;
	}
}
